artifact_location: /home/muhd/Desktop/python-proj/Satelite-deeplearning/research/.../0
creation_time: 1724609140268
experiment_id: '0'
last_update_time: 1724609140268
lifecycle_stage: active
name: Default
